version: '3'
services:
  express:
    build:
        context: .
        dockerfile: ./docker/Dockerfile
    container_name: hello-express
    restart: unless-stopped
    tty: true
    ports:
      - "3000:3000"